# mongo url
mongo.connectionUrl=
mongo.record.database=record


## directories
#source.url=ftp://anonymous@download.europeana.eu:21/dataset/XML/9200515.zip
source.url=ftp://anonymous@download.europeana.eu:21/dataset/XML/
log.dir=.

#
validate=true
validateDB=true
saveCopy=true
external=true
threads=20
