## Record API properties file

# mongo url
mongo.connectionUrl=
mongo.record.database=record


europeana.apikey.serviceurl=

europeana.apikey.jwttoken.signaturekey=
auth.read.enabled=false
auth.write.enabled=false