## Record API properties file

# mongo url
mongo.connectionUrl=mongodb://recorduser1:wRfis830Lpdjw%23@chaos2.eanadev.org/record??compressors=snappy&serverSelectionTimeoutMS=25000&connectTimeoutMS=6000&socketTimeoutMS=35000&directConnection=true&tls=false
mongo.record.database=record


europeana.apikey.serviceurl=

europeana.apikey.jwttoken.signaturekey=
auth.read.enabled=false
auth.write.enabled=false