apiVersion: apps/v1
kind: Deployment
metadata:
  name: record-api-v3-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: record-api-v3
          image: europeana/record-api-v3
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 90
            periodSeconds: 60
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 60
            periodSeconds: 60
          volumeMounts:
            - name: secret
              mountPath: "/opt/app/config/record-api.user.properties"
              readOnly: true
              subPath: record-api.user.properties
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/opt/app/config/record-api.user.properties"
      volumes:
        - name: secret
          secret:
            secretName: record-api-secret