resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: record-api-v3

# expects files to be in the same directory
secretGenerator:
  - name: record-api-secret
    files:
      - record-api.user.properties